### ISSUE TITLE
ClassnotFoundException CryptogramInformationDecoder 

### ISSUE THREAD

**Issue by Nbole** [binaryfoo/emv-bertlv#22]
Hi!, i´m getting this error when i´m trying to decode ( using the "decode" method in RootDecoder class ). This seems to be an issue of ofuscation apparently.

It is possibly a bug ?.

               `Caused by: java.lang.ClassNotFoundException: io.github.binaryfoo.decoders.CryptogramInformationDecoder
                                                                                                    	at java.lang.Class.classForName(Native Method)
                                                                                                    	at java.lang.Class.forName(Class.java:454)
                                                                                                    	at java.lang.Class.forName(Class.java:379)
                                                                                                    	at io.github.binaryfoo.TagMetaData$Companion.load(TagMetaData.kt:86)
                                                                                                    	at io.github.binaryfoo.TagMetaData.load(Unknown Source:2)
                                                                                                    	at io.github.binaryfoo.EmvTags.<clinit>(EmvTags.java:9)
                                                                                                    	at io.github.binaryfoo.RootDecoder.<clinit>(RootDecoder.kt:40) 
                                                                                                    	at com.geopagos.cps.others.tlv.TlvHelper.getTlvs(Unknown Source:5) 
                                                                                                    	at com.geopagos.reader.magicpos.wrapper.MagicPosServiceAdapter$magicPosCallback$1.processNfcTradeResult(MagicPosServiceAdapter.kt:772) 
                                                                                                    	at com.geopagos.reader.magicpos.wrapper.MagicPosServiceAdapter$magicPosCallback$1.onDoPollCardResult(MagicPosServiceAdapter.kt:579) 
                                                                                                    	at com.magicpos.xpos.MPOSService$31.run(MPOSService.java:7457) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:978) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:238) 
                                                                                                    	at android.os.Looper.loop(Looper.java:357) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8098) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "io.github.binaryfoo.decoders.CryptogramInformationDecoder" on path: DexPathList[[zip file "/data/app/~~PPOTaQP2cMfkagmY4r_CEQ==/`

**Comment by nestorsgarzonc** [comment]
You need to add in your proguard rules this line:
`-keep class io.github.binaryfoo.**  { *; }`
